// Replay the independent decision-card regression against an installed static artifact.
// Usage: FREIGHT_REVIEW_PLAYWRIGHT_MODULE=/path/to/playwright/index.mjs node independent_layout.mjs SITE NEW_OUTPUT PINS_JSON CHROMIUM
// Keep independent-oracle.json beside this receiver. The oracle was generated by the pinned Python rules.
import {createServer} from "node:http";
import {readFile,writeFile,mkdir,rm,stat} from "node:fs/promises";
import path from "node:path";
import {fileURLToPath,pathToFileURL} from "node:url";
import {createHash} from "node:crypto";
import assert from "node:assert/strict";
const ROOT=path.dirname(fileURLToPath(import.meta.url));
const [SITE,OUT,PINS,EXECUTABLE]=process.argv.slice(2);
const modulePath=process.env.FREIGHT_REVIEW_PLAYWRIGHT_MODULE;
if(!SITE||!OUT||!PINS||!EXECUTABLE||!modulePath)throw new Error("Set an explicit Playwright module, installed site, NEW output directory, frozen pins and Chromium executable.");
await mkdir(OUT,{recursive:false});
const temporary=path.join(OUT,"temporary");await mkdir(temporary);process.env.TMPDIR=temporary;
const {chromium}=await import(pathToFileURL(modulePath).href);
const files=["index.html","styles.css","app.mjs","model.mjs","data.mjs"];
const sha=b=>createHash("sha256").update(b).digest("hex");
const pins=JSON.parse(await readFile(PINS,"utf8"));
const oraclePath=path.join(ROOT,"independent-oracle.json");
const oracle=JSON.parse(await readFile(oraclePath,"utf8"));
const cases=new Map(oracle.cases.map(c=>[c.id,c]));
const sourceHashes=async()=>Object.fromEntries(await Promise.all(files.map(async n=>[n,sha(await readFile(path.join(SITE,n)))])));
assert.deepStrictEqual(await sourceHashes(),pins);
const checks=[],pageErrors=[],consoleErrors=[],external=[],screenshots=[],requests=new Set(),servedHashes={};
let browser,server,origin,browserVersion;
async function check(name,fn){try{await fn();checks.push({name,passed:true});}catch(e){checks.push({name,passed:false,error:e.stack||String(e)});}}
async function capture(page,name,{fullPage=false,selector=null}={}){
 const target=path.join(OUT,name+".png");
 if(selector)await page.locator(selector).screenshot({path:target});
 else{await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);});await page.screenshot({path:target,fullPage});}
 screenshots.push({name:path.basename(target),sha256:sha(await readFile(target))});
}
const dollars=c=>"$"+Math.floor(c/100).toLocaleString("en-US")+"."+String(c%100).padStart(2,"0");
async function apply(page,c){
 const details=page.locator("details.terms");if(!(await details.evaluate(e=>e.open)))await details.locator("summary").click();
 for(const [key,value] of Object.entries(c.scenario)){
  const control=page.locator("#"+key);
  if(typeof value==="boolean")await control.setChecked(value);
  else await control.fill(value===null?"":key.endsWith("_cents")?(value/100).toFixed(2):String(value));
 }
 assert.equal(await page.locator("#invalid-state").isVisible(),false);
 assert.equal(await page.locator("#download").isDisabled(),false);
 assert.equal(await page.locator("#supported-amount").innerText(),
  c.expected.stop.status==="exception"?"No automatic claim":dollars(c.expected.stop.amount_cents));
 assert.equal(await page.locator("#billed-amount").innerText(),dollars(c.scenario.detention_cents));
 assert.deepStrictEqual(await page.locator("#findings [data-code]").evaluateAll(es=>es.map(e=>e.dataset.code)),c.expected.flags.map(f=>f.code));
}
async function geometry(page,name){
 const g=await page.evaluate(()=>{
  const rect=r=>({left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height});
  const card=document.querySelector(".decision-card").getBoundingClientRect();
  const textRects=e=>{const range=document.createRange();range.selectNodeContents(e);
   return [...range.getClientRects()].filter(r=>r.width>0&&r.height>0).map(rect);};
  const amount=textRects(document.getElementById("supported-amount")),billed=textRects(document.getElementById("billed-amount"));
  const allText=[...document.querySelectorAll("#supported-amount,#billed-amount,#amount-caption,#decision-explanation,.decision-aside>span,.decision-top>span")].flatMap(e=>textRects(e).map(r=>({element:e.id||e.className,...r})));
  const clipped=allText.filter(r=>r.left<card.left-1||r.right>card.right+1||r.top<card.top-1||r.bottom>card.bottom+1);
  const overlaps=amount.some(a=>billed.some(b=>Math.min(a.right,b.right)>Math.max(a.left,b.left)+1&&Math.min(a.bottom,b.bottom)>Math.max(a.top,b.top)+1));
  const controls=[...document.querySelectorAll("input,button,summary")].filter(e=>e.getClientRects().length).map(e=>({id:e.id||e.textContent.trim().slice(0,40),...rect(e.getBoundingClientRect())}));
  return {viewport:innerWidth,document:document.documentElement.scrollWidth,card:rect(card),amount,billed,allText,clipped,overlaps,
   controlsOutsideViewport:controls.filter(r=>r.left< -1||r.right>innerWidth+1)};
 });
 await writeFile(path.join(OUT,name+"-geometry.json"),JSON.stringify(g,null,2)+"\n");
 await capture(page,name,{selector:".decision-card"});
 assert(g.document<=g.viewport+1,"Document horizontal overflow: "+JSON.stringify(g));
 assert.equal(g.controlsOutsideViewport.length,0,"Controls outside viewport: "+JSON.stringify(g));
 assert.equal(g.clipped.length,0,"Decision text clipped: "+JSON.stringify(g));
 assert.equal(g.overlaps,false,"Decision amounts overlap: "+JSON.stringify(g));
}
try{
 server=createServer(async(req,res)=>{
  const pathname=new URL(req.url,"http://127.0.0.1").pathname;requests.add(pathname);
  const file=pathname==="/"?"index.html":pathname.slice(1);
  if(!files.includes(file)){res.writeHead(404);return res.end("Not found");}
  try{const b=await readFile(path.join(SITE,file));servedHashes[file]=sha(b);
   res.writeHead(200,{"Content-Type":file.endsWith(".html")?"text/html; charset=utf-8":file.endsWith(".css")?"text/css; charset=utf-8":"text/javascript; charset=utf-8","Cache-Control":"no-store"});res.end(b);
  }catch{res.writeHead(500);res.end("Read failure");}
 });
 await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));origin="http://127.0.0.1:"+server.address().port;
 browser=await chromium.launch({executablePath:EXECUTABLE,headless:true,downloadsPath:temporary});browserVersion=browser.version();
 for(const width of [1440,390,320]){
  const context=await browser.newContext({viewport:{width,height:width===1440?1000:844},isMobile:width<500,hasTouch:width<500,
   timezoneId:width===1440?"America/Los_Angeles":"Pacific/Auckland",locale:"en-US"});
  await context.route("**/*",route=>{
   const u=route.request().url();if(u.startsWith(origin+"/")||u.startsWith("blob:"+origin))return route.continue();
   external.push(u);return route.abort();
  });
  const page=await context.newPage();page.on("pageerror",e=>pageErrors.push(e.message));page.on("console",m=>{if(m.type()==="error")consoleErrors.push(m.text());});
  await page.goto(origin+"/",{waitUntil:"networkidle"});await page.locator("#result-content").waitFor({state:"visible"});
  await check("layout-"+width+"-default",async()=>{
   assert.equal(await page.locator("#supported-amount").innerText(),"$131.25");
   assert.equal(await page.locator("#billed-amount").innerText(),"$150.00");
   await capture(page,"resting-"+width,{fullPage:width<500});
   await geometry(page,"layout-"+width+"-default");
  });
  for(const id of ["maximum-independent-lines-automatic-sum","exit-24h-inclusive","capped-then-parse-warning"]){
   await check("layout-"+width+"-"+id,async()=>{
    await apply(page,cases.get(id));
    await geometry(page,"layout-"+width+"-"+id);
   });
  }
  await context.close();
 }
 await check("source-custody-and-no-runtime-or-external-errors",async()=>{
  assert.deepStrictEqual(pageErrors,[]);assert.deepStrictEqual(consoleErrors,[]);assert.deepStrictEqual(external,[]);
  assert.deepStrictEqual(servedHashes,pins);assert.deepStrictEqual(await sourceHashes(),pins);
 });
}catch(e){checks.push({name:"receiver-setup-or-unhandled-failure",passed:false,error:e.stack||String(e)});}
finally{
 if(browser)await browser.close();if(server)await new Promise(resolve=>server.close(resolve));
 await rm(temporary,{recursive:true,force:true});
}
let portClosed=true;if(origin){try{await fetch(origin+"/",{signal:AbortSignal.timeout(1000)});portClosed=false;}catch{}}
const receipt={schema:"freight-whatif.independent-layout-receipt.v1",node:process.version,browser_version:browserVersion,
 module_sha256:sha(await readFile(modulePath)),executable_sha256:sha(await readFile(EXECUTABLE)),
 runner_sha256:sha(await readFile(fileURLToPath(import.meta.url))),oracle_sha256:sha(await readFile(oraclePath)),
 site_root:SITE,site_sha256:await sourceHashes(),served_sha256:servedHashes,origin,checks,
 passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length,
 page_errors:pageErrors,console_errors:consoleErrors,external_requests:external,requested_paths:[...requests].sort(),screenshots,
 cleanup:{browser_disconnected:!browser||!browser.isConnected(),server_closed:!server||!server.listening,loopback_port_closed:portClosed,owned_temporary_profile_root_removed:await stat(temporary).then(()=>false,()=>true)},
 limits:"Focused changed-CSS receiving in actual headless Chromium desktop/emulated mobile. Earlier direct rule/export/input/keyboard receiving remains bound to unchanged app/model/data/HTML hashes."};
const target=path.join(OUT,"layout-receipt.json");await writeFile(target,JSON.stringify(receipt,null,2)+"\n");
console.log(JSON.stringify({passed:receipt.passed,failed:receipt.failed,failures:checks.filter(c=>!c.passed),
 receipt:target,receipt_sha256:sha(await readFile(target)),cleanup:receipt.cleanup}));
if(receipt.failed||!portClosed)process.exitCode=1;
